name: Integration specs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker images
      run: cd todo-api && docker-compose build
    - name: Prepare Postgres for unit tests
      run: cd todo-api && docker-compose run test bundle exec rails db:create db:migrate
    - name: Run unit test
      run: cd todo-api && docker-compose run test
    - name: cd todo-api  Prepare Postgres for integration tests
      run: cd todo-api && docker-compose run web bundle exec rails db:create db:migrate
    - name: Run integration specs
      run: cd todo-api && docker-compose run integration_test
